<?php $this->subtitle('Toernooien', $this->url(array('module' => 'tournamentplanner', 'controller' => 'tournament', 'action' => 'index'))) ?>
<?php $this->subtitle($this->tournament->name, $this->url(array('controller' => 'tournament', 'action' => 'read', 'id' => $this->tournament->id))) ?>
<?php $this->subtitle('Veld toekennen') ?>

<div class="section">
  <?php echo $this->partial('tournamentfield/_modify.phtml', array('action' => 'create')) ?>
</div>