<?php $this->subtitle('Toernooien', $this->url(array('module' => 'tournamentplanner', 'controller' => 'tournament', 'action' => 'index'))) ?>
<?php $this->subtitle($this->tournament->name, $this->url(array('controller' => 'tournament', 'action' => 'read', 'id' => $this->tournament->id))) ?>
<?php $this->subtitle($this->group->name) ?>

<h3>Eigenschappen</h3>
<div class="section">
  <table class="properties">
    <tr>
      <td class="name">Naam</td>
      <td class="value"><?php echo $this->escape($this->group->name)?></td>
    </tr>
  </table>
  <br />
  <form class="admin-button" method="get" action="<?php echo $this->url(array('action' => 'update')) ?>">
    <input type="hidden" name="id" value="<?php echo $this->group->id?>" />
    <button type="submit">Wijzig <img src="ats2015/general/images/icons/16x16/edit.png" style="vertical-align: middle" /></button>
  </form>
</div>

<h3>Teams</h3>
<div class="section">
  <table>
    <tr>
      <th style="width: 400px">Naam</th>
      <th style="width: 90px"></th>
      <th></th>
    </tr>
    <?php foreach ($this->teams as $team): ?>
    <tr>
      <td><a href="<?php echo $this->url(array('controller' => 'team', 'action' => 'read', 'id' => $team->id)) ?>"><?php echo $this->escape($team->name) ?></a></td>
      <td>
        <a href="<?php echo $this->url(array('controller' => 'groupteam', 'action' => 'move', 'id' => $team->group_teams[0]->id, 'count' => -1)) ?>"><img src="ats2015/general/images/icons/16x16/arrow_up_blue.png" /></a> 
        <a href="<?php echo $this->url(array('controller' => 'groupteam', 'action' => 'move', 'id' => $team->group_teams[0]->id, 'count' => 1)) ?>"><img src="ats2015/general/images/icons/16x16/arrow_down_green.png" /></a>
      </td>
      <td>
        <a href="<?php echo $this->url(array('controller' => 'groupteam', 'action' => 'delete', 'id' => $team->group_teams[0]->id)) ?>" title="Verwijder team uit poule" onclick="return confirm('Weet u zeker dat u dit team uit de poule wilt verwijderen en daarmee ook de stand en wedstrijden ervan?')"><img src="ats2015/general/images/icons/16x16/delete2.png" /></a>
      </td>
    </tr>
    <?php endforeach ?>
  </table>
  <br />
  <form class="admin-button" method="get" action="<?php echo $this->url(array('controller' => 'groupteam', 'action' => 'create')) ?>">
    <input type="hidden" name="group_id" value="<?php echo $this->group->id ?>" />
    <button type="submit">Toekennen <img src="ats2015/general/images/icons/16x16/add.png" style="vertical-align: middle" /></button>
  </form>
</div>

<h3>Stand</h3>
<div class="section">
  <?php echo $this->partial('standing/_table.phtml', array('standings' => $this->standings)) ?>
  <br />
  <form class="admin-button" method="get" action="<?php echo $this->url(array('controller' => 'group', 'action' => 'syncstandings')) ?>">
    <input type="hidden" name="id" value="<?php echo $this->group->id?>" />
    <button type="submit">Herbereken stand <img src="ats2015/general/images/icons/16x16/refresh.png" style="vertical-align: middle" /></button>
  </form>
</div>

<h3>Wedstrijden</h3>
<div class="section">
  <?php echo $this->partial('match/_table.phtml', array('matches' => $this->matches, 'hideTournaments' => true, 'hideGroups' => true, 'groupByStartsAt' => false)) ?>
</div>