<?php $this->subtitle('Toernooien', $this->url(array('module' => 'tournamentplanner', 'controller' => 'tournament', 'action' => 'index'))) ?>
<?php $this->subtitle($this->tournament->name, $this->url(array('controller' => 'tournament', 'action' => 'read', 'id' => $this->tournament->id))) ?>
<?php $this->subtitle($this->group->name, $this->url(array('action' => 'read', 'id' => $this->group->id))) ?>
<?php $this->subtitle('wijzig') ?>

<div class="section">
  <?php echo $this->partial('group/_modify.phtml', array('action' => 'update')) ?>
</div>