<?php $this->subtitle('Velden') ?>

<h3>Alle velden</h3>
<div class="section">
  <table>
    <tr>
      <th style="width: 500px">Naam</th>
    </tr>
    <?php foreach ($this->fields as $field): ?>
    <tr>
      <td><a href="<?php echo $this->url(array('action' => 'read', 'id' => $field->id)) ?>"><?php echo $this->escape($field->name) ?></a></td>
    </tr>
    <?php endforeach ?>
  </table>
  <br />
  <form class="admin-button" method="get" action="<?php echo $this->url(array('action' => 'create')) ?>">
    <button type="submit">Toevoegen <img src="ats2015/general/images/icons/16x16/add.png" style="vertical-align: middle" /></button>
  </form>
</div>