<?php
if (!isset($this->hideGroups)) { $this->hideGroups = false; }
if (!isset($this->hideTournaments)) { $this->hideTournaments = false; }
if (!isset($this->showEdits)) { $this->showEdits = false; }
$this->showEdits = true;
if (!isset($this->groupByStartsAt)) { $this->groupByStartsAt = true; }
if (!isset($this->highlightTeamId)) { $this->highlightTeamId = -1; }

?>
<table>
  <tr>
    <th>Datum</th>
    <th>Tijd</th>
    <th style="width: 30px">Veld</th>
    <?php if (!$this->hideTournaments): ?>
    <th style="width: 200px">Toernooi</th>
    <?php endif ?>
    <?php if (!$this->hideGroups): ?>
    <th style="width: 70px">Poule</th>
    <?php endif ?>
    <th style="width: 250px">Thuis</th>
    <th></th>
    <th style="width: 250px">Uit</th>
    <th colspan="3">Uitslag</th>
    <?php if ($this->showEdits): ?>
    <th></th>
    <?php endif ?>
  </tr>
  <?php $prevMatch = null ?>
  <?php foreach ($this->matches as $i => $match): ?>
  <?php $isNewGroup = ($prevMatch === null || $prevMatch->starts_at != $match->starts_at) ?>
  <tr <?php if ($isNewGroup && $i>0 && $this->groupByStartsAt): ?>class="first-of-group"<?php endif?>>
    <td style="text-align: right">
      <?php if ($isNewGroup || !$this->groupByStartsAt): ?>
      <?php echo $this->locale()->getFormatter()->formatDate($match->starts_at, 'short', "Y-m-d H:i:s") ?>
      <?php endif ?>
    </td>
    <td style="text-align: right">
      <?php if ($isNewGroup || !$this->groupByStartsAt): ?>
      <?php echo $this->locale()->getFormatter()->formatTime($match->starts_at, 'short', "Y-m-d H:i:s") ?>
      <?php endif ?>
    </td>
    <td><a href="<?php echo $this->url(array('controller' => 'field', 'action' => 'read', 'id' => $match->field->id)) ?>"><?php echo $this->escape($match->field->name) ?></a></td>
    <?php if (!$this->hideTournaments): ?>
    <td><a href="<?php echo $this->url(array('controller' => 'tournament', 'action' => 'read', 'id' => $match->group->tournament->id)) ?>"><?php echo $this->escape($match->group->tournament->name) ?></a></td>
    <?php endif ?>
    <?php if (!$this->hideGroups): ?>
    <td><a href="<?php echo $this->url(array('controller' => 'group', 'action' => 'read', 'id' => $match->group->id)) ?>"><?php echo $this->escape($match->group->name) ?></a></td>
    <?php endif ?>
    <td style="<?php if ($this->highlightTeamId == $match->home_team_id):?>font-weight: bold;<?php endif ?>"><a href="<?php echo $this->url(array('controller' => 'team', 'action' => 'read', 'id' => $match->home_team_id)) ?>"><?php echo $this->escape($match->home_team->name) ?></a></td>
    <td>-</td>
    <td style="<?php if ($this->highlightTeamId == $match->away_team_id):?>font-weight: bold;<?php endif ?>"><a href="<?php echo $this->url(array('controller' => 'team', 'action' => 'read', 'id' => $match->away_team_id)) ?>"><?php echo $this->escape($match->away_team->name) ?></a></td>
    <td><?php echo $match->goals_home ?></td>
    <td>-</td>
    <td><?php echo $match->goals_away ?></td>
    <?php if ($this->showEdits): ?>
    <td><a href="<?php echo $this->url(array('controller' => 'match', 'action' => 'update', 'id' => $match->id, 'form[returnUrl]' => $this->url(array(), null, false))) ?>"><img src="ats2015/general/images/icons/16x16/edit.png" /></a></td>
    <?php endif ?>
  </tr>
  <?php $prevMatch = $match ?>
  <?php endforeach ?>
</table>